export const todoConstants = {
    GET_LIST: 'GET_LIST',
    TODO_FAILURE: 'TODO_FAILURE',
    CREATE_TODO: 'CREATE_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    LIST_REQUEST: 'LIST_REQUEST',
    REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',
    REMOVE_TODO_FAIL: 'REMOVE_TODO_FAIL',

    FINISHED_TODO:'FINISHED_TODO',
    FINISHED_TODO_FAIL:'FINISHED_TODO_FAIL',

    RECOVER_TODO:'RECOVER_TODO',
    RECOVER_TODO_FAIL:'RECOVER_TODO_FAIL',
    FINISH_TODO_EDITION: 'FINISH_TODO_EDITION',
    FINISH_TODO_EDITION_FAIL :'FINISH_TODO_EDITION_FAIL'
};
